### ISSUE TITLE
checklist/proposal for items to cover during the opening meeting

### ISSUE THREAD

**Issue by jdkent** [brainhack-uiowa/2020-brainhack#33]
- [x] introduce all committee members
- [x] give reason why we are doing this/what we hope to accomplish
- [x] mention code of conduct (expectations of participant interactions)
  - identify contact person for code of conduct violations
- [x] introduce people with python/programming expertise helping
  - Adam Harding
  - Jose Jimenez
  - Zoheb Khan
  - Jiefeng Jiang(?)
- [x] register for meeting
- [x] go over communication channels (slack/zoom)
  - (still want to mention hubs even if not going to primarily use it, pending committee approval)
- [x] go over the main concepts covered in the material
- [x] send a poll to get feedback on the pacing of the tutorials.
- [x] announce ice-breaker activity
  - (could use up goer 5 again to describe your work/research): https://splasho.com/upgoer5/
  - give participants ~3 minutes to complete the exercise
- [x] while participants are writing, host can create breakout rooms to place experienced python users with novice users.
- [x] move everyone into breakout rooms to discuss questions/material (fewer than 10 per group ideally, to encourage everyone's participation).
- [x] ~20-30 minutes people either log off or return to the main room to ask more questions or talk more about python.
  - what the most surprising concept/thing you learned from the episode?
  - what is something you still feel hazy about?
- [x] debrief and decide what material to cover next week (just the committee + python/programming experts)
